### ISSUE TITLE
Substituting Reserved Words when not Needed

### ISSUE THREAD

**Issue by cwfitzgerald** [yanorestes/rockstar-py#14]
Hey it's me again!

The following code should compile, setting `my wallet` to 7, as far as my reading of the standard in https://github.com/cwfitzgerald/rockstar-webpiler/issues/1 goes, but rockstar-py substitutes in `-` instead of 7.

Side note: I really should put together a compiler test suite that goes through all the edge cases that can come up :)

**Comment by yanorestes** [comment]
The official docs are clear about that - "**As long as the next symbol is not a reserved keyword**, the rest of the line is treated as a decimal number "

**Comment by cwfitzgerald** [comment]
I think we need some clarification on the spec, because I think both of our readings are perfectly reasonable. I'm reading that as "as long as the next symbol isn't one of the reserved keywords listed above" and you're reading it as "as long as the next symbol isn't one of the reserved keywords anywhere in the language". Both perfectly valid. I would argue that it should be interpreted the first way, as therefore `My wallet is without` is a meaningful statement, reasonable for a rocker to make. Your interpretation makes it semantically meaningless, and should be a parser error as there's no other valid construct to make of it.

**Comment by yanorestes** [comment]
My implementation doens't give any parser error no matter what, that's the point of it - at least for now. It'll try to transpile the code. If the output Python file fails to run, then you know the rockstar code probably had an error. I get your point - `My wallet is without` is not ambiguous as `My wallet is nothing` is, but the fact is `My wallet is nothing` is **not** ambiguous, as it will always be treated as `My wallet is null`. So it doesn't make sense the only reserved keywords the docs are talking about here are the True/False/null aliases, since there is no need to that.

I'll close this issue while we wait for clarification.

**Comment by cwfitzgerald** [comment]
I think these problems arise from having to go all language lawyer on a spec that was written for fun in a brief amount of time :) 

Are you going to open the issue for clarification or should I?
