### ISSUE TITLE
Two number types

### ISSUE THREAD

**Issue by pplewka** [yanorestes/rockstar-py#15]
Right now the transpiler doesn't ensure correct number types.
   ```
Put 421 into my heart
Put 421.0 into my soul
Shout my soul over 2
Say my heart over 2
```
Results in 
```
210.5
210
```
It should be either all int

```
210
210
```
or all float

```
210.5
210.5
```

**Comment by yanorestes** [comment]
The transpiler is based on Python 3. It uses Python 3 code to create Python 3 code. You're running the output program using the Python 2 intepreter, that's why it goes like this. Use Python 3 and you'll be fine!

**Comment by pplewka** [comment]
Thanks. I forgot ``python`` points to ``python2`` on my machine. So this will work with a Python 3 interpreter, because the division always returns float. 
But the underlying issue is still there. One variable starts as int and the other one as float.
float are imprecise. int aren't. A large float will cut off digits at its end. A large int won't.
So results may be different, if a number is written with .0 or without.

But this can change results only, if the numbers get really big , so it isn't really that important

**Comment by yanorestes** [comment]
This doesn't make proper sense. Floating point numbers are imprecise in Python (as they are in every language by definition). But there is no imprecise float number that can be precisely represented by the type int. Adding .0 to the number will never interfere into the result, never (you can try it out), because there's no rounding errors with .0. Imprecise float numbers would be even more Imprecise. `0.1 + 0.2` would result in `0.30000000000000004`, which is Imprecise, but not as much as the int representation - `0`. The solution here would be using the Decimal type, which I'll consider, but I don't think it's really worth it

**Comment by pplewka** [comment]
Maybe you could add .0 to all number literals without it.
This way there would be no int and everything would always behave like a float.
e.g. 100 -> 100.0 and 42.0 would stay the same
